# Generated by Django 5.1.7 on 2025-05-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpresponse',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
