# Generated by Django 5.1.7 on 2025-03-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
