# Generated by Django 5.1.7 on 2025-04-06 21:04

import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_helprequest_email_helprequest_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
